apiVersion: score.dev/v1b1
kind: Workload
metadata:
  name: springbootex
spec:
  resources:
    db:
      type: postgres
    api-dns:
      type: dns
  container:
    variables:
      CONNECTION_STRING: jdbc:postgresql://${externals.workdb.host}:${externals.workdb.port}/${externals.workdb.name}
  routes:
    resources.api-dns.host:
	    /v1/users:8080
	      match: prefix
